version: '3'
services: 
  client:
    build: ./client
    ports: 
      - '3000:3000'
    volumes: 
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment: 
      env_file: .env
      NODE_ENV: development
    stdin_open: true
  server:
    build: ./server
    ports: 
      - '4004:4004'
    volumes: 
      - ./server:/usr/src/app
    environment: 
      env_file: .env
      NODE_ENV: development
    stdin_open: true
    
